# Generated by Django 6.0.5 on 2026-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafespot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafenea',
            options={'verbose_name': 'Cafenea', 'verbose_name_plural': 'Cafenele'},
        ),
        migrations.AlterModelOptions(
            name='recenzie',
            options={'verbose_name': 'Recenzie', 'verbose_name_plural': 'Recenzii'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roluri'},
        ),
        migrations.AlterModelOptions(
            name='utilizator',
            options={'verbose_name': 'Utilizator', 'verbose_name_plural': 'Utilizatori'},
        ),
        migrations.AddField(
            model_name='cafenea',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='cafespot'),
        ),
        migrations.AddField(
            model_name='cafenea',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
