# Generated by Django 6.0.5 on 2026-05-30 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafespot', '0002_alter_cafenea_options_alter_recenzie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizator',
            name='cafenele_favorite',
        ),
        migrations.AddField(
            model_name='cafenea',
            name='utilizatori_care_au_favorizat',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
