# Generated by Django 6.0.5 on 2026-05-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafespot', '0003_remove_utilizator_cafenele_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizator',
            name='cafenele_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorizata_de', to='cafespot.cafenea'),
        ),
    ]
